### ISSUE TITLE
Support use without nvidia-docker

### ISSUE THREAD

**Issue by dhood** [osrf/ariac-docker#5]

**Comment by dhood** [comment]
When we are not running gzclient, maybe errors like the following won't appear:
```
process[startup_ariac-3]: started with pid [103]
[startup_ariac-3] process has finished cleanly
log file: /root/.ros/log/dd45cee4-3b28-11e7-9387-0242ac120016/startup_ariac-3*.log
Gazebo multi-robot simulator, version 7.7.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

X Error of failed request:  GLXBadDrawable
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  48
  Current serial number in output stream:  48
[ INFO] [1495043237.037819335]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[ INFO] [1495043237.038157139]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 127.0.0.1
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Aborted (core dumped)
================================================================================REQUIRED process [gazebo-4] has died!
process has died [pid 122, exit code 134, cmd /opt/ros/indigo/lib/gazebo_ros/gzserver -u --verbose -e ode -r --record_path=/root/.ariac/log/gazebo /tmp/ariac/gear.world joint_states:=ariac/joint_states __name:=gazebo __log:=/root/.ros/log/dd45cee4-3b28-11e7-9387-0242ac120016/gazebo-4.log].
log file: /root/.ros/log/dd45cee4-3b28-11e7-9387-0242ac120016/gazebo-4*.log
Initiating shutdown!
================================================================================
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/controller_manager/controller_manager", line 63, in <module>
    controller_manager_interface.load_controller(c)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/controller_manager/controller_manager_interface.py", line 64, in load_controller
```

**Comment by dhood** [comment]
gpu support removed in https://github.com/osrf/ariac-docker/pull/6
